// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuCVsDfvHoNdRpPcc3GT2zASIftbrwrhM',
    appId: '1:900700705090:web:fc0adda4e0371eeba538db',
    messagingSenderId: '900700705090',
    projectId: 'asistenciaupeu-bc8fe',
    authDomain: 'asistenciaupeu-bc8fe.firebaseapp.com',
    storageBucket: 'asistenciaupeu-bc8fe.firebasestorage.app',
    measurementId: 'G-6RMGYDJ176',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO96Gs_5cH9PAjNK9EUK3_ceQYID_8_LA',
    appId: '1:900700705090:android:eff7bdb7d53f2a64a538db',
    messagingSenderId: '900700705090',
    projectId: 'asistenciaupeu-bc8fe',
    storageBucket: 'asistenciaupeu-bc8fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe9ZLnxf57cxF8tXCdny07V9xVjVh3moM',
    appId: '1:900700705090:ios:9eaa7d3950683925a538db',
    messagingSenderId: '900700705090',
    projectId: 'asistenciaupeu-bc8fe',
    storageBucket: 'asistenciaupeu-bc8fe.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.asistenciaUpeu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe9ZLnxf57cxF8tXCdny07V9xVjVh3moM',
    appId: '1:900700705090:ios:9eaa7d3950683925a538db',
    messagingSenderId: '900700705090',
    projectId: 'asistenciaupeu-bc8fe',
    storageBucket: 'asistenciaupeu-bc8fe.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.asistenciaUpeu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuCVsDfvHoNdRpPcc3GT2zASIftbrwrhM',
    appId: '1:900700705090:web:4fafb88f231e4f33a538db',
    messagingSenderId: '900700705090',
    projectId: 'asistenciaupeu-bc8fe',
    authDomain: 'asistenciaupeu-bc8fe.firebaseapp.com',
    storageBucket: 'asistenciaupeu-bc8fe.firebasestorage.app',
    measurementId: 'G-02TV872F6M',
  );
}
